### ISSUE TITLE
Anchor Links

### ISSUE THREAD

**Issue by TitusKirch** [HanashiDev/dev.hanashi.wsc.faq#21]

**Comment by TitusKirch** [comment]
@Hanashi @Krymonota Is that even needed now that we have our own pages for questions? What do you think?

**Comment by Krymonota** [comment]
@TitusKirch If it's not a big deal to implement anchor links (the only problem I see at the moment is that the page header would cover the question being jumped to), we could always add them because they don't bother anyone. However, I don't see any urgency for this at the moment as we have dedicated question pages now. Perhaps a future contributor might want to implement this feature at some point, so at least I'd keep the issue open 🙂

**Comment by Hanashi** [comment]
Currently, we won't implement this. So I will close this until a user want this feature :)
